
version: "1.0"

services:
  go-server:
    container_name: "go-server-test"
    build:
      context: ./go-server
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - monitoring
