
version: "1.0"

services:
  go-server:
    container_name: "go-server-test"
    build:
      context: ./go-server
      dockerfile: dockerFile
    ports:
      - "9000:9000"
    volumes:
      - go-logs:/app/logs
    networks:
      - monitoring

volumes:
  go-logs:

networks:
  monitoring:
    external: true