
version: "1.0"

services:
  go-server:
    container_name: "go-server-test"
    build:
      context: ./go-server
      dockerfile: dockerFile
    ports:
      - "9000:9000"
    volumes:
      - go-logs:/app/logs
    networks:
      - monitoring
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - go-logs:/logs
      - ./promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - go-server
    networks:
      - monitoring
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
    networks:
      - monitoring

alloy:
    image: grafana/alloy:v1.8.1
    container_name: alloy
    ports:
      - "12345:12345"     # HTTP server for Alloy UI and control
      - "4317:4317"       # OTLP gRPC port for receiving logs from applications
    volumes:
      - go-logs:/app/logs
      - ./config.alloy:/etc/alloy/config.alloy
    command: ["--config.file=/etc/alloy/config.alloy"]
    depends_on:
      - loki
    networks:
      - monitoring

volumes:
  go-logs:

networks:
  monitoring:
    external: true